## @file
# Azure Pipeline build file for building a platform.
#
# Platform: QemuQ35
# OS: Ubuntu
# Toolchain: GCC
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: makubacki
      name: makubacki/mu_devops
      ref: test_nuget_publishing

variables:
- group: architectures-arm64
- group: tool-chain-ubuntu-gcc

jobs:
  - template: templates/Job-Ubuntu-GCC5.yml
