author_string: Microsoft Core UEFI
copyright_string: Copyright (c) Microsoft Corporation.
description_string: QEMU Q35 RELEASE Platform Firmware
license: dummy text
name: TEST.Mu.QemuQ35.FW.RELEASE
project_url: https://microsoft.github.com/mu
server_url: https://pkgs.dev.azure.com/projectmu/mu/_packaging/Mu-Public/nuget/v3/index.json
tags_string: ''
