## @file
# Azure Pipeline build file for building a platform.
#
# Platform: QemuQ35
# OS: Ubuntu
# Toolchain: GCC
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
- name: publish_to_nuget
  displayName: Publish Build to NuGet
  type: boolean
  default: false
- name: version_patch
  displayName: Patch Version (0-65535)
  type: number
  default: 0

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: makubacki
      name: makubacki/mu_devops
      ref: test_nuget_publishing

variables:
- group: architectures-x86-64
- group: tool-chain-ubuntu-gcc
- name: package
  value: QemuQ35Pkg
- name: version.patch
  value: ${{ parameters.version_patch }}
- template: ../Version.yaml

name: v$(version.major).$(version.minor).${{ parameters.version_patch }} Build_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
  - job: Platform_CI
    variables:
      should_run: true
      run_flags: "SHUTDOWN_AFTER_RUN=TRUE QEMU_HEADLESS=TRUE EMPTY_DRIVE=TRUE"

    # Use matrix to speed up the build process
    strategy:
        matrix:

          QemuQ35_DEBUG:
            Build.File: "Platforms/$(package)/PlatformBuild.py"
            Build.Arch: $(arch_list)
            Build.Flags: ""
            Build.Target: "DEBUG"
            Config.Target: "Debug"
            Run.Flags: $(run_flags)
            Run: $(should_run)

          QemuQ35_RELEASE:
            Build.File: "Platforms/$(package)/PlatformBuild.py"
            Build.Arch: $(arch_list)
            Build.Flags: ""
            Build.Target: "RELEASE"
            Config.Target: "Release"
            Run.Flags: $(run_flags)
            Run: $(should_run)

          # NOOPT build too big to fit in FVs
          #QemuQ35_NOOPT:
          #  Build.File: "Platforms/$(package)/PlatformBuild.py"
          #  Build.Arch: $(arch_list)
          #  Build.Flags: ""
          #  Build.Target: "NOOPT"
          #  Run.Flags: $(run_flags)
          #  Run: $(should_run)
    workspace:
      clean: all

    pool:
      vmImage: $(vm_image)

    container: ghcr.io/tianocore/containers/fedora-35-test:latest

    steps:
    - script: echo "##vso[task.prependpath]/home/vsts_azpcontainer/.local/bin"
      displayName: Add User Local Bin to Path
    - template: Steps/BuildPlatform.yml@mu_devops
      parameters:
        tool_chain_tag: $(tool_chain_tag)
        build_pkg: $(package)
        build_target: $(Build.Target)
        build_arch: $(Build.Arch)
        build_file: $(Build.File)
        build_flags: $(Build.Flags)
        run_flags: $(Run.Flags)
        install_tools: false
        artifacts_identifier: '$(package) $(Build.Target)'
        artifacts_binary: |
          **/QEMUQ35_*.fd

    - ${{ if eq(parameters.publish_to_nuget, true) }}:
      - template: Steps/NuGet.yml@mu_devops
        parameters:
          artifacts_identifier: '$(package) $(Build.Target)'
          license_file_path: $(Build.SourcesDirectory)/License.txt
          nuget_package_config_file_path: $(Build.SourcesDirectory)/Platforms/$(package)/NugetPublishing/$(Config.Target)Config.yaml
          nuget_package_version: $(version.major).$(version.minor).$(version.patch)
