## @file
# Azure Pipeline build file for building platforms with VS.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

jobs:
- template: templates/Job-VisualStudio-Platform.yml
