## @file
# Azure Pipeline build file to perform a release in this repo.
#
# Note: This file should be invoked immediately after a release has been published
#       on GitHub.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

trigger: none
pr: none

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: makubacki
      name: makubacki/mu_devops
      ref: test_nuget_publishing

name: $(Date:yyyyMMdd)$(Rev:.r) Mu Tiano Platforms Release

stages:
- stage: Build QEMU Q35
  jobs:
    - template: ../Platforms/QemuQ35Pkg/.azurepipelines/templates/Job-Ubuntu-GCC5.yml
    - template: ../Platforms/QemuQ35Pkg/.azurepipelines/templates/Job-Windows-VS.yml

- stage: Build QEMU SBSA
  dependsOn: [] # Build in parallel with the previous stage
  jobs:
    - template: ../Platforms/QemuSbsaPkg/.azurepipelines/templates/Job-Ubuntu-GCC5.yml

- stage: Publish Release Artifacts
  dependsOn:
  - Build QEMU Q35
  - Build QEMU SBSA
  jobs:
  - template: Publish.yml
