## @file
# Azure Pipeline build file to perform a release in this repo.
#
# Note: This file should be invoked immediately after a release has been published
#       on GitHub.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

trigger: none
pr: none

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/v2.3.0

name: $(Date:yyyyMMdd)$(Rev:.r) Mu Tiano Platforms Release

stages:
- stage: BuildQemuPlatforms
  displayName: Build QEMU Platforms
  jobs:
    - template: templates/Job-Gcc-Platform.yml
    - template: templates/Job-VisualStudio-Platform.yml

- stage: PublishReleaseArtifacts
  displayName: Publish Release Artifacts
  dependsOn:
  - BuildQemuPlatforms
  jobs:
    - template: templates/Job-Publish.yml
