## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

trigger: none

pr:
- dev/*
- release/*

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: IA32,X64
    do_ci_build: true
    do_ci_setup: false
    do_non_ci_build: false
    do_non_ci_setup: true
    do_pr_eval: true
    packages: QemuQ35Pkg
    target_list: NO-TARGET
    tool_chain_tag: GCC5
    vm_image: ubuntu-latest

